type User {
  id: Int!
  email: String!
  name: String
}

type Query {
  allUsers: [User!]
}

type Mutation {
  signUpUser(data: UserCreateInput!): User!
}

input UserCreateInput {
  email: String!
  name: String
}